# Generated by Django 5.0.2 on 2024-03-22 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(default='users/profile_pictures/default.jpg', upload_to='users/profile_pictures'),
        ),
    ]
