# Generated by Django 5.0.1 on 2024-02-20 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_search', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authinfo',
            name='date_format',
        ),
        migrations.AlterField(
            model_name='authinfo',
            name='token',
            field=models.TextField(null=True),
        ),
    ]
