# Generated by Django 5.0.1 on 2024-02-20 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_search', '0002_remove_authinfo_date_format_alter_authinfo_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authinfo',
            name='request_body',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='authinfo',
            name='request_headers',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='searchinfo',
            name='request_headers',
            field=models.JSONField(null=True),
        ),
    ]
