# Generated by Django 4.2.10 on 2024-02-25 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussionBoard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='replyTo',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
