# Generated by Django 5.0.2 on 2024-03-11 03:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_purchase"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchase",
            name="quantity",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]
