# Generated by Django 5.0.2 on 2024-03-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_purchase_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="url",
            field=models.URLField(blank=True, max_length=350, null=True),
        ),
    ]
