# Generated by Django 5.0.2 on 2024-03-23 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_product_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="order_id",
            field=models.CharField(default="", max_length=150, unique=True),
        ),
    ]
