# Generated by Django 5.0.2 on 2024-03-23 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_purchase_order_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchase",
            name="order_id",
            field=models.CharField(default="", max_length=150),
        ),
    ]
